
DROP SCHEMA public cascade;
CREATE SCHEMA public;

-- tables
-- Table: arquivos
CREATE TABLE arquivos (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_arquivos varchar(300) ,
    extensao varchar(300),
    url_arquivo varchar(300) not null,
    tipo varchar(300),
    colaborador_id int not null,
    "createdAt" date NOT NULL DEFAULT now(),
    "updatedAt" date 
);

-- Table: acessos
CREATE TABLE acessos (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargos_id int ,
    nivel_acesso int ,
    "createdAt" date NOT NULL DEFAULT now(),
    "updatedAt" date 
);

-- Table: cargos
CREATE TABLE cargos (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departamento_id int ,
    cargo varchar(300) ,
    "createdAt" date NOT NULL DEFAULT now(),
    "updatedAt" date 
);

-- Table: colaboradors
CREATE TABLE colaboradors (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargos_id int ,
    gestor_id int ,
    nome varchar(300) ,
    rg varchar(200) unique,
    email varchar(300) unique,
    senha varchar(300) ,
    naturalidade varchar(200),
    nacionalidade varchar(200),
    estado_civil varchar(200),
    genero varchar(200),
    raca varchar(100),
    telefone varchar(300) ,
    data_nascimento varchar(300) ,
    pesquisa_desligamento varchar(300),
    status varchar(200) ,
    dominio varchar(300) ,
    tipo_desligamento varchar(300),
    "createdAt" date NOT NULL DEFAULT now(),
    "updatedAt" date 
);

-- Table: contratos
CREATE TABLE contratos (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    colaborador_id int ,
    faixa_salarial int ,
    auxilio_creche int ,
    vale_refeicao int ,
    distrato varchar(45) ,
    contrato_trabalho varchar(200) ,
    codigo_conduta_etica varchar(40) ,
    vale_transporte int ,
    base varchar(300) ,
    "data_Admissao date ",
    plano_saude varchar(40) ,
    "createdAt" date NOT NULL DEFAULT now(),
    "updatedAt" int ,
    data_desligamento date 
);

-- Table: dados_academicos
CREATE TABLE dados_academicos (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    colaborador_id int ,
    formacao varchar(200) ,
    cursos varchar(200) ,
    termo_PI varchar(200) ,
    linguas varchar(200) ,
    "createdAt" date NOT NULL DEFAULT now(),
    "updatedAt" date 
);

-- Table: departamentos
CREATE TABLE departamentos (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area varchar(300) ,
    head varchar(300) ,
    head_id int ,
    "createdAt" date NOT NULL DEFAULT now(),
    "updatedAt" date 
);

-- Table: enderecos
CREATE TABLE enderecos (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rua varchar(300),
    estado varchar(200) ,
    regiao varchar(300) ,
    cep varchar(300) ,
    cidade varchar(300) ,
    bairro varchar(300) ,
    complemento varchar(300) ,
    colaborador_id int ,
    "createdAt" date NOT NULL DEFAULT now(),
    "updatedAt" date 
    );

-- Table: grade_cursos
CREATE TABLE grade_cursos (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trilha_aprendizados_id int ,
    nome_curso varchar(200) ,
    "createdAt" date NOT NULL DEFAULT now(),
    "updatedAt" date 
);

-- Table: pessoa_fisicas
CREATE TABLE pessoa_fisicas (
    colaborador_id int NOT NULL PRIMARY KEY,
    cpf varchar(15) unique,
    "createdAt" date NOT NULL DEFAULT now(),
    "updatedAt" date 
);

-- Table: pessoa_juridicas
CREATE TABLE pessoa_juridicas (
    colaborador_id int NOT NULL PRIMARY KEY,
    cnpj varchar(20) unique,
    empresa_contratada varchar(300) ,
    tempo_formalizacao varchar(300) ,
    natureza_juridica varchar(300) ,
    data_fundacao varchar(300) ,
    "createdAt" date NOT NULL DEFAULT now(),
    "updatedAt" date 
);

-- Table: trilha_aprendizados
CREATE TABLE trilha_aprendizados (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_fisicas_colaborador_id int ,
    status_curso varchar(200) ,
    data_inicio date ,
    data_fim date ,
    "createdAt" date NOT NULL DEFAULT now(),
    "updatedAt" date 
);

-- foreign keys

-- Reference: arquivos_colaborador (table: colaboradors)
ALTER TABLE arquivos ADD CONSTRAINT arquivo_colaborador FOREIGN KEY (colaborador_id)
    REFERENCES colaboradors (id);

-- Reference: acesso_cargo (table: acessos)
ALTER TABLE acessos ADD CONSTRAINT acesso_cargo FOREIGN KEY (cargos_id)
    REFERENCES cargos (id);

-- Reference: cargo_colaborador (table: cargos)
ALTER TABLE colaboradors ADD CONSTRAINT colaboradors_cargo FOREIGN KEY (cargos_id)
    REFERENCES cargos (id);
    
-- Reference: Colaborador_Colaborador (table: Colaboradors)
ALTER TABLE colaboradors ADD CONSTRAINT colaboradors_colaborador FOREIGN KEY (gestor_id)
    REFERENCES colaboradors (id);

-- Reference: departamento_cargo (table: Cargos)
ALTER TABLE cargos ADD CONSTRAINT departamento_cargo FOREIGN KEY  (departamento_id)
    REFERENCES departamentos (id) ON DELETE SET NULL;

-- Reference: Contrato_Colaborador (table: Contratos)
ALTER TABLE contratos ADD CONSTRAINT contrato_colaborador FOREIGN KEY (colaborador_id)
    REFERENCES colaboradors (id);

-- Reference: Dados_Academicos_Colaborador (table: Dados_Academicos)
ALTER TABLE dados_academicos ADD CONSTRAINT dados_academicos_colaborador FOREIGN KEY (colaborador_id)
    REFERENCES colaboradors (id);

-- Reference: Endereco_Colaborador (table: Colaboradors)
ALTER TABLE enderecos ADD CONSTRAINT endereco_colaborador FOREIGN KEY (colaborador_id)
    REFERENCES colaboradors (id);

-- Reference: Grade_Curso_Trilha_Aprendizado (table: Grade_Cursos)
ALTER TABLE grade_cursos ADD CONSTRAINT grade_curso_trilha_aprendizado FOREIGN KEY (trilha_aprendizados_id)
    REFERENCES trilha_aprendizados (id);

-- Reference: Pessoa_Fisica_Colaborador (table: Pessoa_Fisicas)
ALTER TABLE pessoa_fisicas ADD CONSTRAINT pessoa_fisica_colaborador FOREIGN KEY (colaborador_id)
    REFERENCES colaboradors (id);

-- Reference: Pessoa_Juridica_Colaborador (table: Pessoa_Juridicas)
ALTER TABLE pessoa_juridicas ADD CONSTRAINT pessoa_juridica_colaborador FOREIGN KEY (colaborador_id)
    REFERENCES colaboradors (id);

-- Reference: Trilha_Aprendizado_Pessoa_Fisica (table: Trilha_Aprendizados)
ALTER TABLE trilha_aprendizados ADD CONSTRAINT trilha_aprendizado_pessoa_fisica FOREIGN KEY (id)
    REFERENCES pessoa_fisicas (colaborador_id);

insert into departamentos(id, area, "createdAt") values (1, 'Administracão', '2022-04-13');
insert into cargos(id, departamento_id, cargo, "createdAt") values (1, 1, 'Administrador', '2022-04-13');
insert into colaboradors(id, cargos_id, nome, email, senha, "createdAt") values (1, 1, 'CEO', 'ceo@ionic.com', 'ceoionic', '2022-04-13');
insert into colaboradors(id, cargos_id, nome, email, senha, "createdAt") values (2, 1, 'Admin', 'admin@ionic.com', 'adminionic', '2022-04-13');
